[manga-reader-dev]
image=fedora:latest
additional_packages="gtk3-devel webkit2gtk4.1-devel libsoup3-devel gcc-c++ nodejs golang pkgconf-pkg-config"
init=false
nvidia=false
pull=true
root=false
replace=true
# Esto montará tu carpeta actual dentro del contenedor
volume="$PWD:/work"
# Establece el directorio de trabajo al entrar
entrypoint="cd /work && zsh" 

# commands to run when creating the container
# distrobox assemble create
# distrobox enter manga-reader-dev
# distrobox enter manga-reader-dev -- wails dev
#
# distrobox stop manga-reader-dev
# distrobox stop -y manga-reader-dev