import '@testing-library/jest-dom'

vi.mock('wailsjs/runtime', () => ({
  EventsOn: vi.fn(() => vi.fn()),
  EventsOff: vi.fn(),
  EventsEmit: vi.fn(),
  EventsOnce: vi.fn(),
  EventsOnMultiple: vi.fn(),
  EventsOffAll: vi.fn(),
  LogPrint: vi.fn(),
  LogTrace: vi.fn(),
  LogDebug: vi.fn(),
  LogError: vi.fn(),
  LogFatal: vi.fn(),
  LogInfo: vi.fn(),
  LogWarning: vi.fn(),
  WindowReload: vi.fn(),
  WindowReloadApp: vi.fn(),
  WindowSetAlwaysOnTop: vi.fn(),
  WindowSetSystemDefaultTheme: vi.fn(),
  WindowSetLightTheme: vi.fn(),
  WindowSetDarkTheme: vi.fn(),
  WindowCenter: vi.fn(),
  WindowSetTitle: vi.fn(),
  WindowFullscreen: vi.fn(),
  WindowUnfullscreen: vi.fn(),
  WindowIsFullscreen: vi.fn(() => Promise.resolve(false)),
  WindowSetSize: vi.fn(),
  WindowGetSize: vi.fn(() => Promise.resolve({ w: 1024, h: 768 })),
  WindowSetMaxSize: vi.fn(),
  WindowSetMinSize: vi.fn(),
  WindowSetPosition: vi.fn(),
  WindowGetPosition: vi.fn(() => Promise.resolve({ x: 0, y: 0 })),
  WindowHide: vi.fn(),
  WindowShow: vi.fn(),
  WindowMaximise: vi.fn(),
  WindowToggleMaximise: vi.fn(),
  WindowUnmaximise: vi.fn(),
  WindowIsMaximised: vi.fn(() => Promise.resolve(false)),
  WindowMinimise: vi.fn(),
  WindowUnminimise: vi.fn(),
  WindowIsMinimised: vi.fn(() => Promise.resolve(false)),
  WindowIsNormal: vi.fn(() => Promise.resolve(true)),
  WindowSetBackgroundColour: vi.fn(),
  ScreenGetAll: vi.fn(() => Promise.resolve([])),
  BrowserOpenURL: vi.fn(),
  Environment: vi.fn(() => Promise.resolve({
    buildType: 'desktop',
    platform: 'windows',
    arch: 'amd64',
  })),
  Quit: vi.fn(),
  Hide: vi.fn(),
  Show: vi.fn(),
  ClipboardGetText: vi.fn(() => Promise.resolve('')),
  ClipboardSetText: vi.fn(() => Promise.resolve(true)),
  OnFileDrop: vi.fn(),
  OnFileDropOff: vi.fn(),
  CanResolveFilePaths: vi.fn(() => false),
  ResolveFilePaths: vi.fn(),
  InitializeNotifications: vi.fn(() => Promise.resolve()),
  CleanupNotifications: vi.fn(() => Promise.resolve()),
  IsNotificationAvailable: vi.fn(() => Promise.resolve(false)),
  RequestNotificationAuthorization: vi.fn(() => Promise.resolve(false)),
  CheckNotificationAuthorization: vi.fn(() => Promise.resolve(false)),
  SendNotification: vi.fn(() => Promise.resolve()),
  SendNotificationWithActions: vi.fn(() => Promise.resolve()),
  RegisterNotificationCategory: vi.fn(() => Promise.resolve()),
  RemoveNotificationCategory: vi.fn(() => Promise.resolve()),
  RemoveAllPendingNotifications: vi.fn(() => Promise.resolve()),
  RemovePendingNotification: vi.fn(() => Promise.resolve()),
  RemoveAllDeliveredNotifications: vi.fn(() => Promise.resolve()),
  RemoveDeliveredNotification: vi.fn(() => Promise.resolve()),
  RemoveNotification: vi.fn(() => Promise.resolve()),
}))

vi.mock('wailsjs/go/main/App', () => {
  const fn = vi.fn()
  const asyncFn = vi.fn(() => Promise.resolve())

  const createMock = (defaultValue?: unknown) => {
    const mock = vi.fn(() => Promise.resolve(defaultValue))
    return mock
  }

  return {
    AddBaseFolder: asyncFn,
    AddDownloadedFolder: createMock(''),
    AddDownloadedSeries: createMock(''),
    AddFolder: createMock({ id: '', path: '', isSeries: false, coverImage: '' }),
    AddHistory: asyncFn,
    AddSeries: createMock({ id: '', path: '', isSeries: false, coverImage: '' }),
    CheckForUpdate: createMock({ hasUpdate: false }),
    ClearAllData: asyncFn,
    ClearDownloadHistory: asyncFn,
    ClearHistory: asyncFn,
    ClearLibrary: asyncFn,
    ClearSeries: asyncFn,
    ClearThumbnailCache: asyncFn,
    ColorizeImage: createMock({ image: '', success: false }),
    ColorizerGetServerURL: createMock(''),
    ColorizerGetStatus: createMock({}),
    ColorizerHealthCheck: createMock(false),
    ColorizerInstall: asyncFn,
    ColorizerIsInstalled: createMock(false),
    ColorizerIsRunning: createMock(false),
    ColorizerRestartServer: asyncFn,
    ColorizerStartServer: asyncFn,
    ColorizerStopServer: asyncFn,
    CreateLibrary: createMock({ id: '', name: '', path: '' }),
    DeleteLibrary: asyncFn,
    DownloadUpdate: asyncFn,
    ExploreFolder: createMock([]),
    FetchMangaInfo: createMock({}),
    GetAVIFStatus: createMock(''),
    GetActiveLibraryID: createMock(''),
    GetBaseFolders: createMock([]),
    GetChapterNavigation: createMock({}),
    GetCurrentVersion: createMock(''),
    GetDefaultLibrary: createMock({ id: '', name: '', path: '' }),
    GetDownloadAlgorithmConfig: createMock({}),
    GetDownloadHistory: createMock([]),
    GetExplorerRootViewMode: createMock('grid'),
    GetExplorerSortPreference: createMock({ sortBy: 'name', sortOrder: 'asc' }),
    GetExplorerSortPreferences: createMock({}),
    GetFolderAutoOrder: createMock([]),
    GetFolderGridSize: createMock(0),
    GetFolderInfo: createMock({ path: '', name: '', isSeries: false, coverImage: '' }),
    GetFolderInfoShallow: createMock({ path: '', name: '', isSeries: false, coverImage: '' }),
    GetFolderNavigation: createMock({}),
    GetFolderNavigationWithSort: createMock({}),
    GetFolderOrder: createMock([]),
    GetFolderOriginalOrder: createMock([]),
    GetFolderViewMode: createMock('grid'),
    GetHistory: createMock([]),
    GetHistoryEntry: createMock(null),
    GetHistoryViewMode: createMock('list'),
    GetImageOrder: createMock([]),
    GetImages: createMock([]),
    GetImagesShallow: createMock([]),
    GetImagesShallowWithSort: createMock([]),
    GetImagesWithSort: createMock([]),
    GetLibraries: createMock([]),
    GetLibrary: createMock([]),
    GetLibraryByID: createMock(null),
    GetLocalNetworkAddress: createMock(''),
    GetLocalNetworkServerStatus: createMock(false),
    GetOneShotSortBy: createMock('name'),
    GetOneShotSortOrder: createMock('asc'),
    GetOriginalOrder: createMock([]),
    GetPinnedFolders: createMock([]),
    GetPinnedImages: createMock([]),
    GetSeries: createMock([]),
    GetSeriesDetailsSortPreference: createMock({ sortBy: 'name', sortOrder: 'asc' }),
    GetSeriesDetailsSortPreferences: createMock({}),
    GetSeriesSortBy: createMock('name'),
    GetSeriesSortOrder: createMock('asc'),
    GetSettings: createMock(null),
    GetSubfolders: createMock([]),
    GetTabs: createMock({ tabs: [], activeTab: '' }),
    GetThumbnail: createMock(''),
    GetUpdateState: createMock({}),
    GetViewerState: createMock(null),
    GetWebPStatus: createMock(''),
    HasCustomOrder: createMock(false),
    HasFolderAutoOrder: createMock(false),
    HasFolderCustomOrder: createMock(false),
    IsSeries: createMock(false),
    IsUpdatePending: createMock(false),
    LoadImageAsBase64: createMock(''),
    OpenInFileManager: asyncFn,
    OpenLibraryFile: createMock({ id: '', name: '', path: '' }),
    PinFolder: asyncFn,
    PinImage: asyncFn,
    PreloadThumbnails: asyncFn,
    PromoteToAutoOrder: createMock([]),
    RemoveBaseFolder: asyncFn,
    RemoveDownloadJob: asyncFn,
    RemoveHistory: asyncFn,
    RemoveLibraryEntry: asyncFn,
    RemoveSeries: asyncFn,
    ReorderPinnedFolders: asyncFn,
    ReorderPinnedImages: asyncFn,
    ResetFolderAutoOrder: asyncFn,
    ResetFolderOrder: asyncFn,
    ResetImageOrder: asyncFn,
    ResetSettings: asyncFn,
    ResolveFolder: createMock(''),
    ResumeIncompleteDownloads: asyncFn,
    SaveColorizedImage: createMock(''),
    SaveColorizedImageAuto: createMock(''),
    SaveDownloadAlgorithmConfig: asyncFn,
    SaveImageOrder: asyncFn,
    SaveMultipleColorizedImages: createMock([]),
    SaveMultipleColorizedImagesAuto: createMock([]),
    SaveSettings: asyncFn,
    SaveTabs: asyncFn,
    SaveViewerState: asyncFn,
    SaveWindowState: asyncFn,
    SearchExplorer: createMock([]),
    SelectFolder: createMock(''),
    SelectLibraryFile: createMock(''),
    SetExplorerRootViewMode: asyncFn,
    SetExplorerSortPreference: asyncFn,
    SetFolderAutoOrder: asyncFn,
    SetFolderGridSize: asyncFn,
    SetFolderOrder: asyncFn,
    SetFolderViewMode: asyncFn,
    SetHistoryViewMode: asyncFn,
    SetOneShotSortBy: asyncFn,
    SetOneShotSortOrder: asyncFn,
    SetSeriesDetailsSortPreference: asyncFn,
    SetSeriesSortBy: asyncFn,
    SetSeriesSortOrder: asyncFn,
    SetThumbnailsPaused: asyncFn,
    StartDownload: createMock(''),
    SwitchLibrary: asyncFn,
    ToggleLocalNetworkServer: asyncFn,
    UnpinFolder: asyncFn,
    UnpinImage: asyncFn,
    UpdateSettings: asyncFn,
    UpdateTaskbarIcon: asyncFn,
    WasJustUpdated: createMock(false),
    WindowIsMaximised: createMock(false),
    WindowMaximise: asyncFn,
    WindowMinimise: asyncFn,
    WindowToggleMaximise: asyncFn,
    WindowUnmaximise: asyncFn,
  }
})

const mockApp = {
  AddBaseFolder: vi.fn(),
  AddDownloadedFolder: vi.fn(),
  AddDownloadedSeries: vi.fn(),
  AddFolder: vi.fn(),
  AddHistory: vi.fn(),
  AddSeries: vi.fn(),
  CheckForUpdate: vi.fn(),
  ClearAllData: vi.fn(),
  ClearDownloadHistory: vi.fn(),
  ClearHistory: vi.fn(),
  ClearLibrary: vi.fn(),
  ClearSeries: vi.fn(),
  ClearThumbnailCache: vi.fn(),
  ColorizeImage: vi.fn(),
  ColorizerGetServerURL: vi.fn(),
  ColorizerGetStatus: vi.fn(),
  ColorizerHealthCheck: vi.fn(),
  ColorizerInstall: vi.fn(),
  ColorizerIsInstalled: vi.fn(),
  ColorizerIsRunning: vi.fn(),
  ColorizerRestartServer: vi.fn(),
  ColorizerStartServer: vi.fn(),
  ColorizerStopServer: vi.fn(),
  CreateLibrary: vi.fn(),
  DeleteLibrary: vi.fn(),
  DownloadUpdate: vi.fn(),
  ExploreFolder: vi.fn(),
  FetchMangaInfo: vi.fn(),
  GetAVIFStatus: vi.fn(),
  GetActiveLibraryID: vi.fn(),
  GetBaseFolders: vi.fn(),
  GetChapterNavigation: vi.fn(),
  GetCurrentVersion: vi.fn(),
  GetDefaultLibrary: vi.fn(),
  GetDownloadAlgorithmConfig: vi.fn(),
  GetDownloadHistory: vi.fn(),
  GetExplorerRootViewMode: vi.fn(),
  GetExplorerSortPreference: vi.fn(),
  GetExplorerSortPreferences: vi.fn(),
  GetFolderAutoOrder: vi.fn(),
  GetFolderGridSize: vi.fn(),
  GetFolderInfo: vi.fn(),
  GetFolderInfoShallow: vi.fn(),
  GetFolderNavigation: vi.fn(),
  GetFolderNavigationWithSort: vi.fn(),
  GetFolderOrder: vi.fn(),
  GetFolderOriginalOrder: vi.fn(),
  GetFolderViewMode: vi.fn(),
  GetHistory: vi.fn(),
  GetHistoryEntry: vi.fn(),
  GetHistoryViewMode: vi.fn(),
  GetImageOrder: vi.fn(),
  GetImages: vi.fn(),
  GetImagesShallow: vi.fn(),
  GetImagesShallowWithSort: vi.fn(),
  GetImagesWithSort: vi.fn(),
  GetLibraries: vi.fn(),
  GetLibrary: vi.fn(),
  GetLibraryByID: vi.fn(),
  GetLocalNetworkAddress: vi.fn(),
  GetLocalNetworkServerStatus: vi.fn(),
  GetOneShotSortBy: vi.fn(),
  GetOneShotSortOrder: vi.fn(),
  GetOriginalOrder: vi.fn(),
  GetPinnedFolders: vi.fn(),
  GetPinnedImages: vi.fn(),
  GetSeries: vi.fn(),
  GetSeriesDetailsSortPreference: vi.fn(),
  GetSeriesDetailsSortPreferences: vi.fn(),
  GetSeriesSortBy: vi.fn(),
  GetSeriesSortOrder: vi.fn(),
  GetSettings: vi.fn(),
  GetSubfolders: vi.fn(),
  GetTabs: vi.fn(),
  GetThumbnail: vi.fn(),
  GetUpdateState: vi.fn(),
  GetViewerState: vi.fn(),
  GetWebPStatus: vi.fn(),
  HasCustomOrder: vi.fn(),
  HasFolderAutoOrder: vi.fn(),
  HasFolderCustomOrder: vi.fn(),
  IsSeries: vi.fn(),
  IsUpdatePending: vi.fn(),
  LoadImageAsBase64: vi.fn(),
  OpenInFileManager: vi.fn(),
  OpenLibraryFile: vi.fn(),
  PinFolder: vi.fn(),
  PinImage: vi.fn(),
  PreloadThumbnails: vi.fn(),
  PromoteToAutoOrder: vi.fn(),
  RemoveBaseFolder: vi.fn(),
  RemoveDownloadJob: vi.fn(),
  RemoveHistory: vi.fn(),
  RemoveLibraryEntry: vi.fn(),
  RemoveSeries: vi.fn(),
  ReorderPinnedFolders: vi.fn(),
  ReorderPinnedImages: vi.fn(),
  ResetFolderAutoOrder: vi.fn(),
  ResetFolderOrder: vi.fn(),
  ResetImageOrder: vi.fn(),
  ResetSettings: vi.fn(),
  ResolveFolder: vi.fn(),
  ResumeIncompleteDownloads: vi.fn(),
  SaveColorizedImage: vi.fn(),
  SaveColorizedImageAuto: vi.fn(),
  SaveDownloadAlgorithmConfig: vi.fn(),
  SaveImageOrder: vi.fn(),
  SaveMultipleColorizedImages: vi.fn(),
  SaveMultipleColorizedImagesAuto: vi.fn(),
  SaveSettings: vi.fn(),
  SaveTabs: vi.fn(),
  SaveViewerState: vi.fn(),
  SaveWindowState: vi.fn(),
  SearchExplorer: vi.fn(),
  SelectFolder: vi.fn(),
  SelectLibraryFile: vi.fn(),
  SetExplorerRootViewMode: vi.fn(),
  SetExplorerSortPreference: vi.fn(),
  SetFolderAutoOrder: vi.fn(),
  SetFolderGridSize: vi.fn(),
  SetFolderOrder: vi.fn(),
  SetFolderViewMode: vi.fn(),
  SetHistoryViewMode: vi.fn(),
  SetOneShotSortBy: vi.fn(),
  SetOneShotSortOrder: vi.fn(),
  SetSeriesDetailsSortPreference: vi.fn(),
  SetSeriesSortBy: vi.fn(),
  SetSeriesSortOrder: vi.fn(),
  SetThumbnailsPaused: vi.fn(),
  StartDownload: vi.fn(),
  SwitchLibrary: vi.fn(),
  ToggleLocalNetworkServer: vi.fn(),
  UnpinFolder: vi.fn(),
  UnpinImage: vi.fn(),
  UpdateSettings: vi.fn(),
  UpdateTaskbarIcon: vi.fn(),
  WasJustUpdated: vi.fn(),
  WindowIsMaximised: vi.fn(),
  WindowMaximise: vi.fn(),
  WindowMinimise: vi.fn(),
  WindowToggleMaximise: vi.fn(),
  WindowUnmaximise: vi.fn(),
}

Object.defineProperty(window, 'go', {
  value: { main: { App: mockApp } },
  writable: true,
  configurable: true,
})

Object.defineProperty(window, 'runtime', {
  value: {
    EventsOn: vi.fn(() => vi.fn()),
    EventsOff: vi.fn(),
    EventsEmit: vi.fn(),
    EventsOnce: vi.fn(),
    EventsOnMultiple: vi.fn(),
    EventsOffAll: vi.fn(),
    LogPrint: vi.fn(),
    LogTrace: vi.fn(),
    LogDebug: vi.fn(),
    LogError: vi.fn(),
    LogFatal: vi.fn(),
    LogInfo: vi.fn(),
    LogWarning: vi.fn(),
    WindowReload: vi.fn(),
    WindowReloadApp: vi.fn(),
    WindowSetAlwaysOnTop: vi.fn(),
    WindowSetSystemDefaultTheme: vi.fn(),
    WindowSetLightTheme: vi.fn(),
    WindowSetDarkTheme: vi.fn(),
    WindowCenter: vi.fn(),
    WindowSetTitle: vi.fn(),
    WindowFullscreen: vi.fn(),
    WindowUnfullscreen: vi.fn(),
    WindowIsFullscreen: vi.fn(() => Promise.resolve(false)),
    WindowSetSize: vi.fn(),
    WindowGetSize: vi.fn(() => Promise.resolve({ w: 1024, h: 768 })),
    WindowSetMaxSize: vi.fn(),
    WindowSetMinSize: vi.fn(),
    WindowSetPosition: vi.fn(),
    WindowGetPosition: vi.fn(() => Promise.resolve({ x: 0, y: 0 })),
    WindowHide: vi.fn(),
    WindowShow: vi.fn(),
    WindowMaximise: vi.fn(),
    WindowToggleMaximise: vi.fn(),
    WindowUnmaximise: vi.fn(),
    WindowIsMaximised: vi.fn(() => Promise.resolve(false)),
    WindowMinimise: vi.fn(),
    WindowUnminimise: vi.fn(),
    WindowIsMinimised: vi.fn(() => Promise.resolve(false)),
    WindowIsNormal: vi.fn(() => Promise.resolve(true)),
    WindowSetBackgroundColour: vi.fn(),
    ScreenGetAll: vi.fn(() => Promise.resolve([])),
    BrowserOpenURL: vi.fn(),
    Environment: vi.fn(() => Promise.resolve({
      buildType: 'desktop',
      platform: 'windows',
      arch: 'amd64',
    })),
    Quit: vi.fn(),
    Hide: vi.fn(),
    Show: vi.fn(),
    ClipboardGetText: vi.fn(() => Promise.resolve('')),
    ClipboardSetText: vi.fn(() => Promise.resolve(true)),
    OnFileDrop: vi.fn(),
    OnFileDropOff: vi.fn(),
    CanResolveFilePaths: vi.fn(() => false),
    ResolveFilePaths: vi.fn(),
    InitializeNotifications: vi.fn(() => Promise.resolve()),
    CleanupNotifications: vi.fn(() => Promise.resolve()),
    IsNotificationAvailable: vi.fn(() => Promise.resolve(false)),
    RequestNotificationAuthorization: vi.fn(() => Promise.resolve(false)),
    CheckNotificationAuthorization: vi.fn(() => Promise.resolve(false)),
    SendNotification: vi.fn(() => Promise.resolve()),
  },
  writable: true,
  configurable: true,
})
