/**
 * App - Main application component
 * Simplified and refactored for better separation of concerns
 */

import { Suspense, useMemo, memo } from 'react';
import { useShallow } from 'zustand/react/shallow';
import { MainLayout } from '@components/layout/MainLayout';
import { useTabStore, useSettingsStore } from '@stores';
import { usePanicMode, useAppInitialization, useTabPersistence, useWindowManagement } from '@hooks';
import { ToastProvider, ErrorBoundary } from '@shared/components';
import { LoadingScreen } from '@app/LoadingScreen';
import { renderPage } from '@app/routes';
import { UpdateBanner } from '@components/ui/UpdateBanner';
import './i18n';

// Window.go types are automatically generated by Wails in wailsjs/go/main/App.d.ts
// No need to declare them here

// Page router component with optimized rendering
// Uses per-tab primitive selectors so updating unrelated tab fields (e.g., viewerState)
// does NOT cause unnecessary re-renders of this PageRouter instance.
const PageRouter = memo(function PageRouter({ tabId, isActive = true }: { tabId?: string; isActive?: boolean }) {
    const id = tabId || useTabStore((state: any) => state.activeTabId);

    // Select ONLY page (string primitive) — won't re-render when other tab fields change
    const currentPage = useTabStore((s: any) => {
        const tab = s.tabs.find((t: any) => t.id === id);
        return tab?.page ?? 'home';
    });

    // Select params with shallow compare — stable reference when params object hasn't changed
    const params = useTabStore(useShallow((s: any) => {
        const tab = s.tabs.find((t: any) => t.id === id);
        return tab?.params ?? {};
    }));

    // Memoize page content to prevent unnecessary re-renders
    const pageContent = useMemo(() => {
        return renderPage(currentPage, params, isActive, id);
    }, [currentPage, params, isActive, id]);

    return (
        <div
            className="h-full w-full"
            style={{
                display: isActive ? 'block' : 'none',
                visibility: isActive ? 'visible' : 'hidden'
            }}
        >
            {pageContent}
        </div>
    );
});

function PageContainer() {
    // Subscribe to stable tab IDs only (not full tab objects) to prevent
    // cascading re-renders when any tab's internal state changes.
    const tabIds = useTabStore(useShallow((state: any) => state.tabs.map((t: any) => t.id)));
    const activeTabId = useTabStore((state: any) => state.activeTabId);
    const tabMemorySaving = useSettingsStore((state: any) => state.tabMemorySaving);

    if (tabMemorySaving) {
        return <PageRouter key={activeTabId} isActive={true} />;
    }

    return (
        <div className="h-full w-full relative">
            {tabIds.map((id: string) => (
                <PageRouter
                    key={id}
                    tabId={id}
                    isActive={id === activeTabId}
                />
            ))}
        </div>
    );
}


function App() {
    // Initialize application hooks
    usePanicMode();
    useAppInitialization();
    useTabPersistence();
    useWindowManagement();

    return (
        <ErrorBoundary
            onError={(error, errorInfo) => {
                // Log error for debugging
                console.error('[App] Error caught by boundary:', error, errorInfo);
            }}
        >
            <Suspense fallback={<LoadingScreen />}>
                <ToastProvider>
                    <MainLayout>
                        <PageContainer />
                    </MainLayout>
                    <UpdateBanner />
                </ToastProvider>
            </Suspense>
        </ErrorBoundary>
    );
}

export default App;
