/**
 * App - Main application component
 */

import { Suspense, useMemo, memo, lazy } from 'react';
import { MainLayout } from './components/layout/MainLayout';

// Lazy load pages for code splitting
// Handle both named and default exports
const HomePage = lazy(() => import('./components/pages/HomePage').then(m => ({ default: m.default || m.HomePage })));
const ViewerPage = lazy(() => import('./features/viewer/ViewerPage').then(m => ({ default: m.default || m.ViewerPage })));
const OneShotPage = lazy(() => import('./components/pages/OneShotPage').then(m => ({ default: m.default || m.OneShotPage })));
const SeriesPage = lazy(() => import('./components/pages/SeriesPage').then(m => ({ default: m.default || m.SeriesPage })));
const SeriesDetailsPage = lazy(() => import('./components/pages/SeriesDetailsPage').then(m => ({ default: m.default || m.SeriesDetailsPage })));
const HistoryPage = lazy(() => import('./components/pages/HistoryPage').then(m => ({ default: m.default || m.HistoryPage })));
const ExplorerPage = lazy(() => import('./components/pages/ExplorerPage').then(m => ({ default: m.ExplorerPage })));
const ThumbnailsPage = lazy(() => import('./components/pages/ThumbnailsPage').then(m => ({ default: m.default || m.ThumbnailsPage })));
const SettingsPage = lazy(() => import('./components/pages/SettingsPage').then(m => ({ default: m.default || m.SettingsPage })));
const DownloadPage = lazy(() => import('./components/pages/DownloadPage').then(m => ({ default: m.DownloadPage })));
import { useTabStore } from './stores/tabStore';
import { useSettingsStore } from './stores/settingsStore';
import { usePanicMode } from './hooks/usePanicMode';
import { useAppInitialization } from './hooks/useAppInitialization';
import { useTabPersistence } from './hooks/useTabPersistence';
import { useWindowManagement } from './hooks/useWindowManagement';
import { ToastProvider } from './components/common/Toast';
import { ErrorBoundary } from './components/common/ErrorBoundary';
import './i18n';

// Window.go types are automatically generated by Wails in wailsjs/go/main/App.d.ts
// No need to declare them here

// Loading component
function LoadingScreen() {
    return (
        <div
            className="flex items-center justify-center h-screen w-screen animate-fade-in"
            style={{ backgroundColor: 'var(--color-surface-primary)' }}
        >
            <div className="flex flex-col items-center gap-4 animate-scale-in">
                {/* Animated logo */}
                <div
                    className="w-16 h-16 rounded-xl flex items-center justify-center"
                    style={{
                        background: 'var(--gradient-accent)',
                        animation: 'rotateLogo 2s ease-in-out infinite'
                    }}
                >
                    <svg
                        width="32"
                        height="32"
                        viewBox="0 0 24 24"
                        fill="white"
                    >
                        <path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm-1 17.93c-3.95-.49-7-3.85-7-7.93 0-.62.08-1.21.21-1.79L9 15v1c0 1.1.9 2 2 2v1.93zm6.9-2.54c-.26-.81-1-1.39-1.9-1.39h-1v-3c0-.55-.45-1-1-1H8v-2h2c.55 0 1-.45 1-1V7h2c1.1 0 2-.9 2-2v-.41c2.93 1.19 5 4.06 5 7.41 0 2.08-.8 3.97-2.1 5.39z" />
                    </svg>
                </div>

                {/* Loading text */}
                <div
                    className="text-lg font-medium animate-pulse-slow"
                    style={{ color: 'var(--color-text-secondary)' }}
                >
                    Loading...
                </div>

                {/* Progress bar */}
                <div
                    className="w-48 h-1 rounded-full overflow-hidden"
                    style={{ backgroundColor: 'var(--color-surface-tertiary)' }}
                >
                    <div
                        className="h-full rounded-full animate-progress"
                        style={{
                            background: 'var(--gradient-accent)',
                            width: '100%'
                        }}
                    />
                </div>
            </div>
        </div>
    );
}

// Page router component with optimized rendering
const PageRouter = memo(function PageRouter({ tabId, isActive = true }: { tabId?: string; isActive?: boolean }) {
    const activeTabIdFromStore = useTabStore(state => state.activeTabId);
    const id = tabId || activeTabIdFromStore;

    // Read page and params from the specific tab, NOT the global navigation store
    // This ensures each tab maintains its own state independently
    const tab = useTabStore(state => state.tabs.find(t => t.id === id));
    const currentPage = tab?.page || 'home';
    const params = tab?.params || {};

    // Create a stable key from params for comparison
    const paramsKey = useMemo(() => {
        return Object.keys(params).sort().map(k => `${k}:${params[k]}`).join('|');
    }, [params]);

    // Memoize page content to prevent unnecessary re-renders
    const pageContent = useMemo(() => {
        return renderPage(currentPage, params, isActive, id);
    }, [currentPage, paramsKey, isActive, id]);

    return (
        <div
            className="h-full w-full"
            style={{
                display: isActive ? 'block' : 'none',
                visibility: isActive ? 'visible' : 'hidden' // Double layer for security against layout shifts
            }}
        >
            {pageContent}
        </div>
    );
});

function PageContainer() {
    const { tabs, activeTabId } = useTabStore();
    const { tabMemorySaving } = useSettingsStore();

    if (tabMemorySaving) {
        return <PageRouter key={activeTabId} isActive={true} />;
    }

    return (
        <div className="h-full w-full relative">
            {tabs.map((tab) => (
                <PageRouter
                    key={tab.id}
                    tabId={tab.id}
                    isActive={tab.id === activeTabId}
                />
            ))}
        </div>
    );
}

// Render page based on current navigation
function renderPage(page: string, params: Record<string, string>, isActive: boolean, tabId?: string): React.ReactNode {
    switch (page) {
        case 'home':
            return <HomePage />;
        case 'viewer':
            return <ViewerPage folderPath={params.folder} isActive={isActive} tabId={tabId} />;
        case 'history':
            return <HistoryPage />;
        case 'oneShot':
            return <OneShotPage />;
        case 'series':
            return <SeriesPage />;
        case 'series-details':
            return <SeriesDetailsPage seriesPath={params.series} tabId={tabId} />;
        case 'settings':
            return <SettingsPage />;
        case 'thumbnails':
            return <ThumbnailsPage folderPath={params.folder} isActive={isActive} tabId={tabId} />;
        case 'explorer':
            return <ExplorerPage isActive={isActive} tabId={tabId} />;
        case 'download':
            return <DownloadPage />;
        default:
            return <HomePage />;
    }
}

function App() {
    // Initialize application hooks
    usePanicMode();
    useAppInitialization();
    useTabPersistence();
    useWindowManagement();

    return (
        <ErrorBoundary
            onError={(error, errorInfo) => {
                // Log error for debugging
                console.error('[App] Error caught by boundary:', error, errorInfo);
            }}
        >
            <Suspense fallback={<LoadingScreen />}>
                <ToastProvider>
                    <MainLayout>
                        <PageContainer />
                    </MainLayout>
                </ToastProvider>
            </Suspense>
        </ErrorBoundary>
    );
}

export default App;
