/**
 * App - Main application component
 * Simplified and refactored for better separation of concerns
 */

import { Suspense, useMemo, memo } from 'react';
import { MainLayout } from '@components/layout/MainLayout';
import { useTabStore, useSettingsStore } from '@stores';
import { usePanicMode, useAppInitialization, useTabPersistence, useWindowManagement } from '@hooks';
import { ToastProvider, ErrorBoundary } from '@shared/components';
import { LoadingScreen } from '@app/LoadingScreen';
import { renderPage } from '@app/routes';
import './i18n';

// Window.go types are automatically generated by Wails in wailsjs/go/main/App.d.ts
// No need to declare them here

// Page router component with optimized rendering
const PageRouter = memo(function PageRouter({ tabId, isActive = true }: { tabId?: string; isActive?: boolean }) {
    const activeTabIdFromStore = useTabStore((state: any) => state.activeTabId);
    const id = tabId || activeTabIdFromStore;

    // Read page and params from the specific tab, NOT the global navigation store
    // This ensures each tab maintains its own state independently
    const tab = useTabStore((state: any) => state.tabs.find((t: any) => t.id === id));
    const currentPage = tab?.page || 'home';
    const params = tab?.params || {};

    // Create a stable key from params for comparison
    const paramsKey = useMemo(() => {
        return Object.keys(params).sort().map(k => `${k}:${params[k]}`).join('|');
    }, [params]);

    // Memoize page content to prevent unnecessary re-renders
    const pageContent = useMemo(() => {
        return renderPage(currentPage, params, isActive, id);
    }, [currentPage, paramsKey, isActive, id]);

    return (
        <div
            className="h-full w-full"
            style={{
                display: isActive ? 'block' : 'none',
                visibility: isActive ? 'visible' : 'hidden' // Double layer for security against layout shifts
            }}
        >
            {pageContent}
        </div>
    );
});

function PageContainer() {
    const tabs = useTabStore((state: any) => state.tabs);
    const activeTabId = useTabStore((state: any) => state.activeTabId);
    const tabMemorySaving = useSettingsStore((state: any) => state.tabMemorySaving);

    if (tabMemorySaving) {
        return <PageRouter key={activeTabId} isActive={true} />;
    }

    return (
        <div className="h-full w-full relative">
            {tabs.map((tab: any) => (
                <PageRouter
                    key={tab.id}
                    tabId={tab.id}
                    isActive={tab.id === activeTabId}
                />
            ))}
        </div>
    );
}


function App() {
    // Initialize application hooks
    usePanicMode();
    useAppInitialization();
    useTabPersistence();
    useWindowManagement();

    return (
        <ErrorBoundary
            onError={(error, errorInfo) => {
                // Log error for debugging
                console.error('[App] Error caught by boundary:', error, errorInfo);
            }}
        >
            <Suspense fallback={<LoadingScreen />}>
                <ToastProvider>
                    <MainLayout>
                        <PageContainer />
                    </MainLayout>
                </ToastProvider>
            </Suspense>
        </ErrorBoundary>
    );
}

export default App;
