// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {persistence} from '../models';
import {explorer} from '../models';
import {downloader} from '../models';
import {series} from '../models';

export function AddBaseFolder(arg1:string):Promise<void>;

export function AddFolder(arg1:string):Promise<persistence.AddFolderResult>;

export function AddHistory(arg1:persistence.HistoryEntry):Promise<void>;

export function AddSeries(arg1:string,arg2:Array<persistence.FolderInfo>,arg3:boolean):Promise<persistence.AddFolderResult>;

export function ClearAllData():Promise<void>;

export function ClearDownloadHistory():Promise<void>;

export function ClearHistory():Promise<void>;

export function ClearLibrary():Promise<void>;

export function ClearSeries():Promise<void>;

export function ClearThumbnailCache():Promise<void>;

export function ExploreFolder(arg1:string):Promise<Array<explorer.ExplorerEntry>>;

export function FetchMangaInfo(arg1:string):Promise<downloader.SiteInfo>;

export function GetBaseFolders():Promise<Array<explorer.BaseFolderEntry>>;

export function GetChapterNavigation(arg1:string):Promise<series.ChapterNavigation>;

export function GetDownloadHistory():Promise<Array<persistence.DownloadJob>>;

export function GetFolderInfo(arg1:string):Promise<persistence.FolderInfo>;

export function GetHistory():Promise<Array<persistence.HistoryEntry>>;

export function GetHistoryEntry(arg1:string):Promise<persistence.HistoryEntry>;

export function GetImageOrder(arg1:string):Promise<Array<string>>;

export function GetImages(arg1:string):Promise<Array<persistence.ImageInfo>>;

export function GetLibrary():Promise<Array<persistence.FolderInfo>>;

export function GetOriginalOrder(arg1:string):Promise<Array<string>>;

export function GetSeries():Promise<Array<series.SeriesEntryWithURLs>>;

export function GetSettings():Promise<persistence.Settings>;

export function GetSubfolders(arg1:string):Promise<Array<persistence.FolderInfo>>;

export function GetThumbnail(arg1:string):Promise<string>;

export function HasCustomOrder(arg1:string):Promise<boolean>;

export function IsSeries(arg1:string):Promise<boolean>;

export function OpenInFileManager(arg1:string):Promise<void>;

export function PreloadThumbnails(arg1:Array<string>):Promise<void>;

export function RemoveBaseFolder(arg1:string):Promise<void>;

export function RemoveDownloadJob(arg1:string):Promise<void>;

export function RemoveHistory(arg1:string):Promise<void>;

export function RemoveLibraryEntry(arg1:string):Promise<void>;

export function RemoveSeries(arg1:string):Promise<void>;

export function ResetImageOrder(arg1:string):Promise<void>;

export function ResolveFolder(arg1:string):Promise<string>;

export function SaveImageOrder(arg1:string,arg2:Array<string>,arg3:Array<string>):Promise<void>;

export function SaveSettings(arg1:persistence.Settings):Promise<void>;

export function SaveWindowState():Promise<void>;

export function SelectFolder():Promise<string>;

export function StartDownload(arg1:string):Promise<string>;

export function UpdateSettings(arg1:Record<string, any>):Promise<void>;

export function WindowIsMaximised():Promise<boolean>;

export function WindowMaximise():Promise<void>;

export function WindowMinimise():Promise<void>;

export function WindowToggleMaximise():Promise<void>;

export function WindowUnmaximise():Promise<void>;
