// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddBaseFolder(arg1) {
  return window['go']['main']['App']['AddBaseFolder'](arg1);
}

export function AddDownloadedFolder(arg1) {
  return window['go']['main']['App']['AddDownloadedFolder'](arg1);
}

export function AddDownloadedSeries(arg1) {
  return window['go']['main']['App']['AddDownloadedSeries'](arg1);
}

export function AddFolder(arg1) {
  return window['go']['main']['App']['AddFolder'](arg1);
}

export function AddHistory(arg1) {
  return window['go']['main']['App']['AddHistory'](arg1);
}

export function AddSeries(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddSeries'](arg1, arg2, arg3);
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function ClearAllData() {
  return window['go']['main']['App']['ClearAllData']();
}

export function ClearDownloadHistory() {
  return window['go']['main']['App']['ClearDownloadHistory']();
}

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function ClearLibrary() {
  return window['go']['main']['App']['ClearLibrary']();
}

export function ClearSeries() {
  return window['go']['main']['App']['ClearSeries']();
}

export function ClearThumbnailCache() {
  return window['go']['main']['App']['ClearThumbnailCache']();
}

export function ColorizeImage(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['ColorizeImage'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function ColorizerGetServerURL() {
  return window['go']['main']['App']['ColorizerGetServerURL']();
}

export function ColorizerGetStatus() {
  return window['go']['main']['App']['ColorizerGetStatus']();
}

export function ColorizerHealthCheck() {
  return window['go']['main']['App']['ColorizerHealthCheck']();
}

export function ColorizerInstall() {
  return window['go']['main']['App']['ColorizerInstall']();
}

export function ColorizerIsInstalled() {
  return window['go']['main']['App']['ColorizerIsInstalled']();
}

export function ColorizerIsRunning() {
  return window['go']['main']['App']['ColorizerIsRunning']();
}

export function ColorizerRestartServer() {
  return window['go']['main']['App']['ColorizerRestartServer']();
}

export function ColorizerStartServer() {
  return window['go']['main']['App']['ColorizerStartServer']();
}

export function ColorizerStopServer() {
  return window['go']['main']['App']['ColorizerStopServer']();
}

export function DownloadUpdate(arg1) {
  return window['go']['main']['App']['DownloadUpdate'](arg1);
}

export function ExploreFolder(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExploreFolder'](arg1, arg2, arg3);
}

export function FetchMangaInfo(arg1) {
  return window['go']['main']['App']['FetchMangaInfo'](arg1);
}

export function GetAVIFStatus() {
  return window['go']['main']['App']['GetAVIFStatus']();
}

export function GetBaseFolders() {
  return window['go']['main']['App']['GetBaseFolders']();
}

export function GetChapterNavigation(arg1) {
  return window['go']['main']['App']['GetChapterNavigation'](arg1);
}

export function GetCurrentVersion() {
  return window['go']['main']['App']['GetCurrentVersion']();
}

export function GetDownloadAlgorithmConfig() {
  return window['go']['main']['App']['GetDownloadAlgorithmConfig']();
}

export function GetDownloadHistory() {
  return window['go']['main']['App']['GetDownloadHistory']();
}

export function GetExplorerRootViewMode() {
  return window['go']['main']['App']['GetExplorerRootViewMode']();
}

export function GetExplorerSortPreference(arg1) {
  return window['go']['main']['App']['GetExplorerSortPreference'](arg1);
}

export function GetExplorerSortPreferences() {
  return window['go']['main']['App']['GetExplorerSortPreferences']();
}

export function GetFolderAutoOrder(arg1) {
  return window['go']['main']['App']['GetFolderAutoOrder'](arg1);
}

export function GetFolderGridSize(arg1) {
  return window['go']['main']['App']['GetFolderGridSize'](arg1);
}

export function GetFolderInfo(arg1) {
  return window['go']['main']['App']['GetFolderInfo'](arg1);
}

export function GetFolderInfoShallow(arg1) {
  return window['go']['main']['App']['GetFolderInfoShallow'](arg1);
}

export function GetFolderNavigation(arg1) {
  return window['go']['main']['App']['GetFolderNavigation'](arg1);
}

export function GetFolderNavigationWithSort(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetFolderNavigationWithSort'](arg1, arg2, arg3);
}

export function GetFolderOrder(arg1) {
  return window['go']['main']['App']['GetFolderOrder'](arg1);
}

export function GetFolderOriginalOrder(arg1) {
  return window['go']['main']['App']['GetFolderOriginalOrder'](arg1);
}

export function GetFolderViewMode(arg1) {
  return window['go']['main']['App']['GetFolderViewMode'](arg1);
}

export function GetHistory() {
  return window['go']['main']['App']['GetHistory']();
}

export function GetHistoryEntry(arg1) {
  return window['go']['main']['App']['GetHistoryEntry'](arg1);
}

export function GetHistoryViewMode() {
  return window['go']['main']['App']['GetHistoryViewMode']();
}

export function GetImageOrder(arg1) {
  return window['go']['main']['App']['GetImageOrder'](arg1);
}

export function GetImages(arg1) {
  return window['go']['main']['App']['GetImages'](arg1);
}

export function GetImagesShallow(arg1) {
  return window['go']['main']['App']['GetImagesShallow'](arg1);
}

export function GetImagesShallowWithSort(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetImagesShallowWithSort'](arg1, arg2, arg3);
}

export function GetImagesWithSort(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetImagesWithSort'](arg1, arg2, arg3);
}

export function GetLibrary() {
  return window['go']['main']['App']['GetLibrary']();
}

export function GetOneShotSortBy() {
  return window['go']['main']['App']['GetOneShotSortBy']();
}

export function GetOneShotSortOrder() {
  return window['go']['main']['App']['GetOneShotSortOrder']();
}

export function GetOriginalOrder(arg1) {
  return window['go']['main']['App']['GetOriginalOrder'](arg1);
}

export function GetSeries() {
  return window['go']['main']['App']['GetSeries']();
}

export function GetSeriesDetailsSortPreference(arg1) {
  return window['go']['main']['App']['GetSeriesDetailsSortPreference'](arg1);
}

export function GetSeriesDetailsSortPreferences() {
  return window['go']['main']['App']['GetSeriesDetailsSortPreferences']();
}

export function GetSeriesSortBy() {
  return window['go']['main']['App']['GetSeriesSortBy']();
}

export function GetSeriesSortOrder() {
  return window['go']['main']['App']['GetSeriesSortOrder']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSubfolders(arg1) {
  return window['go']['main']['App']['GetSubfolders'](arg1);
}

export function GetTabs() {
  return window['go']['main']['App']['GetTabs']();
}

export function GetThumbnail(arg1) {
  return window['go']['main']['App']['GetThumbnail'](arg1);
}

export function GetUpdateState() {
  return window['go']['main']['App']['GetUpdateState']();
}

export function GetViewerState(arg1) {
  return window['go']['main']['App']['GetViewerState'](arg1);
}

export function GetWebPStatus() {
  return window['go']['main']['App']['GetWebPStatus']();
}

export function HasCustomOrder(arg1) {
  return window['go']['main']['App']['HasCustomOrder'](arg1);
}

export function HasFolderAutoOrder(arg1) {
  return window['go']['main']['App']['HasFolderAutoOrder'](arg1);
}

export function HasFolderCustomOrder(arg1) {
  return window['go']['main']['App']['HasFolderCustomOrder'](arg1);
}

export function IsSeries(arg1) {
  return window['go']['main']['App']['IsSeries'](arg1);
}

export function IsUpdatePending() {
  return window['go']['main']['App']['IsUpdatePending']();
}

export function LoadImageAsBase64(arg1) {
  return window['go']['main']['App']['LoadImageAsBase64'](arg1);
}

export function OpenInFileManager(arg1) {
  return window['go']['main']['App']['OpenInFileManager'](arg1);
}

export function PreloadThumbnails(arg1) {
  return window['go']['main']['App']['PreloadThumbnails'](arg1);
}

export function PromoteToAutoOrder(arg1, arg2, arg3) {
  return window['go']['main']['App']['PromoteToAutoOrder'](arg1, arg2, arg3);
}

export function RemoveBaseFolder(arg1) {
  return window['go']['main']['App']['RemoveBaseFolder'](arg1);
}

export function RemoveDownloadJob(arg1) {
  return window['go']['main']['App']['RemoveDownloadJob'](arg1);
}

export function RemoveHistory(arg1) {
  return window['go']['main']['App']['RemoveHistory'](arg1);
}

export function RemoveLibraryEntry(arg1) {
  return window['go']['main']['App']['RemoveLibraryEntry'](arg1);
}

export function RemoveSeries(arg1) {
  return window['go']['main']['App']['RemoveSeries'](arg1);
}

export function ResetFolderAutoOrder(arg1) {
  return window['go']['main']['App']['ResetFolderAutoOrder'](arg1);
}

export function ResetFolderOrder(arg1) {
  return window['go']['main']['App']['ResetFolderOrder'](arg1);
}

export function ResetImageOrder(arg1) {
  return window['go']['main']['App']['ResetImageOrder'](arg1);
}

export function ResetSettings() {
  return window['go']['main']['App']['ResetSettings']();
}

export function ResolveFolder(arg1) {
  return window['go']['main']['App']['ResolveFolder'](arg1);
}

export function ResumeIncompleteDownloads(arg1) {
  return window['go']['main']['App']['ResumeIncompleteDownloads'](arg1);
}

export function SaveColorizedImage(arg1, arg2) {
  return window['go']['main']['App']['SaveColorizedImage'](arg1, arg2);
}

export function SaveColorizedImageAuto(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveColorizedImageAuto'](arg1, arg2, arg3);
}

export function SaveDownloadAlgorithmConfig(arg1) {
  return window['go']['main']['App']['SaveDownloadAlgorithmConfig'](arg1);
}

export function SaveImageOrder(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveImageOrder'](arg1, arg2, arg3);
}

export function SaveMultipleColorizedImages(arg1) {
  return window['go']['main']['App']['SaveMultipleColorizedImages'](arg1);
}

export function SaveMultipleColorizedImagesAuto(arg1, arg2) {
  return window['go']['main']['App']['SaveMultipleColorizedImagesAuto'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SaveTabs(arg1) {
  return window['go']['main']['App']['SaveTabs'](arg1);
}

export function SaveViewerState(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveViewerState'](arg1, arg2, arg3, arg4);
}

export function SaveWindowState() {
  return window['go']['main']['App']['SaveWindowState']();
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SetExplorerRootViewMode(arg1) {
  return window['go']['main']['App']['SetExplorerRootViewMode'](arg1);
}

export function SetExplorerSortPreference(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetExplorerSortPreference'](arg1, arg2, arg3);
}

export function SetFolderAutoOrder(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetFolderAutoOrder'](arg1, arg2, arg3);
}

export function SetFolderGridSize(arg1, arg2) {
  return window['go']['main']['App']['SetFolderGridSize'](arg1, arg2);
}

export function SetFolderOrder(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetFolderOrder'](arg1, arg2, arg3);
}

export function SetFolderViewMode(arg1, arg2) {
  return window['go']['main']['App']['SetFolderViewMode'](arg1, arg2);
}

export function SetHistoryViewMode(arg1) {
  return window['go']['main']['App']['SetHistoryViewMode'](arg1);
}

export function SetOneShotSortBy(arg1) {
  return window['go']['main']['App']['SetOneShotSortBy'](arg1);
}

export function SetOneShotSortOrder(arg1) {
  return window['go']['main']['App']['SetOneShotSortOrder'](arg1);
}

export function SetSeriesDetailsSortPreference(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetSeriesDetailsSortPreference'](arg1, arg2, arg3);
}

export function SetSeriesSortBy(arg1) {
  return window['go']['main']['App']['SetSeriesSortBy'](arg1);
}

export function SetSeriesSortOrder(arg1) {
  return window['go']['main']['App']['SetSeriesSortOrder'](arg1);
}

export function SetThumbnailsPaused(arg1) {
  return window['go']['main']['App']['SetThumbnailsPaused'](arg1);
}

export function StartDownload(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartDownload'](arg1, arg2, arg3);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}

export function UpdateTaskbarIcon(arg1) {
  return window['go']['main']['App']['UpdateTaskbarIcon'](arg1);
}

export function WindowIsMaximised() {
  return window['go']['main']['App']['WindowIsMaximised']();
}

export function WindowMaximise() {
  return window['go']['main']['App']['WindowMaximise']();
}

export function WindowMinimise() {
  return window['go']['main']['App']['WindowMinimise']();
}

export function WindowToggleMaximise() {
  return window['go']['main']['App']['WindowToggleMaximise']();
}

export function WindowUnmaximise() {
  return window['go']['main']['App']['WindowUnmaximise']();
}
