// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddBaseFolder(arg1) {
  return window['go']['main']['App']['AddBaseFolder'](arg1);
}

export function AddFolder(arg1) {
  return window['go']['main']['App']['AddFolder'](arg1);
}

export function AddHistory(arg1) {
  return window['go']['main']['App']['AddHistory'](arg1);
}

export function AddSeries(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddSeries'](arg1, arg2, arg3);
}

export function ClearDownloadHistory() {
  return window['go']['main']['App']['ClearDownloadHistory']();
}

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function ClearLibrary() {
  return window['go']['main']['App']['ClearLibrary']();
}

export function ClearSeries() {
  return window['go']['main']['App']['ClearSeries']();
}

export function ClearThumbnailCache() {
  return window['go']['main']['App']['ClearThumbnailCache']();
}

export function ExploreFolder(arg1) {
  return window['go']['main']['App']['ExploreFolder'](arg1);
}

export function FetchMangaInfo(arg1) {
  return window['go']['main']['App']['FetchMangaInfo'](arg1);
}

export function GetBaseFolders() {
  return window['go']['main']['App']['GetBaseFolders']();
}

export function GetChapterNavigation(arg1) {
  return window['go']['main']['App']['GetChapterNavigation'](arg1);
}

export function GetDownloadHistory() {
  return window['go']['main']['App']['GetDownloadHistory']();
}

export function GetFolderInfo(arg1) {
  return window['go']['main']['App']['GetFolderInfo'](arg1);
}

export function GetHistory() {
  return window['go']['main']['App']['GetHistory']();
}

export function GetHistoryEntry(arg1) {
  return window['go']['main']['App']['GetHistoryEntry'](arg1);
}

export function GetImageOrder(arg1) {
  return window['go']['main']['App']['GetImageOrder'](arg1);
}

export function GetImages(arg1) {
  return window['go']['main']['App']['GetImages'](arg1);
}

export function GetLibrary() {
  return window['go']['main']['App']['GetLibrary']();
}

export function GetOriginalOrder(arg1) {
  return window['go']['main']['App']['GetOriginalOrder'](arg1);
}

export function GetSeries() {
  return window['go']['main']['App']['GetSeries']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSubfolders(arg1) {
  return window['go']['main']['App']['GetSubfolders'](arg1);
}

export function GetThumbnail(arg1) {
  return window['go']['main']['App']['GetThumbnail'](arg1);
}

export function HasCustomOrder(arg1) {
  return window['go']['main']['App']['HasCustomOrder'](arg1);
}

export function IsSeries(arg1) {
  return window['go']['main']['App']['IsSeries'](arg1);
}

export function OpenInFileManager(arg1) {
  return window['go']['main']['App']['OpenInFileManager'](arg1);
}

export function PreloadThumbnails(arg1) {
  return window['go']['main']['App']['PreloadThumbnails'](arg1);
}

export function RemoveBaseFolder(arg1) {
  return window['go']['main']['App']['RemoveBaseFolder'](arg1);
}

export function RemoveDownloadJob(arg1) {
  return window['go']['main']['App']['RemoveDownloadJob'](arg1);
}

export function RemoveHistory(arg1) {
  return window['go']['main']['App']['RemoveHistory'](arg1);
}

export function RemoveLibraryEntry(arg1) {
  return window['go']['main']['App']['RemoveLibraryEntry'](arg1);
}

export function RemoveSeries(arg1) {
  return window['go']['main']['App']['RemoveSeries'](arg1);
}

export function ResetImageOrder(arg1) {
  return window['go']['main']['App']['ResetImageOrder'](arg1);
}

export function ResolveFolder(arg1) {
  return window['go']['main']['App']['ResolveFolder'](arg1);
}

export function SaveImageOrder(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveImageOrder'](arg1, arg2, arg3);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SaveWindowState() {
  return window['go']['main']['App']['SaveWindowState']();
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function StartDownload(arg1) {
  return window['go']['main']['App']['StartDownload'](arg1);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}

export function WindowIsMaximised() {
  return window['go']['main']['App']['WindowIsMaximised']();
}

export function WindowMaximise() {
  return window['go']['main']['App']['WindowMaximise']();
}

export function WindowMinimise() {
  return window['go']['main']['App']['WindowMinimise']();
}

export function WindowToggleMaximise() {
  return window['go']['main']['App']['WindowToggleMaximise']();
}

export function WindowUnmaximise() {
  return window['go']['main']['App']['WindowUnmaximise']();
}
